"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */

import { useEffect,useState } from "react";
import { Button } from "@/components/ui/Button"; import { Card } from "@/components/ui/Card"; import { Select } from "@/components/ui/Select"; import { Textarea } from "@/components/ui/Input";
import { Link } from "@/i18n/navigation";
type Row={id:string;kind:string;name:string;email:string;unionName:string;localName:string;role?:string;offerings:string[];message?:string;status:string;privateNote?:string;createdAt:string;unionId?:string;localId?:string};
const statuses=["new","reviewing","approved","invited","completed","declined"];
export function AccessRequestsInbox(){const [rows,setRows]=useState<Row[]>([]);const [status,setStatus]=useState("");const [error,setError]=useState("");async function load(){const r=await fetch(`/api/site-admin/access-requests${status?`?status=${status}`:""}`);if(!r.ok){setError("Unable to load requests.");return}setRows((await r.json()).items)}useEffect(()=>{void load()},[status]);async function save(row:Row){const r=await fetch(`/api/site-admin/access-requests/${row.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:row.status,unionId:row.unionId||null,localId:row.localId||null,privateNote:row.privateNote||null})});if(!r.ok)setError("Unable to save request.");else await load()}return <div className="space-y-6"><header><h1 className="text-2xl font-bold text-opseu-dark">Beta access requests</h1><p className="mt-2 text-gray-700">Review local interest and route member access requests before sending an invitation.</p></header><Select label="Filter status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All requests</option>{statuses.map(s=><option key={s}>{s}</option>)}</Select>{error?<p role="alert" className="text-red-700">{error}</p>:null}<ul className="space-y-4">{rows.map(row=><li key={row.id}><RequestCard row={row} onSave={save}/></li>)}</ul>{!rows.length?<p className="text-gray-600">No requests match this filter.</p>:null}</div>}
function RequestCard({row,onSave}:{row:Row;onSave:(r:Row)=>Promise<void>}){const [draft,setDraft]=useState(row);return <Card density="compact"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold text-opseu-dark">{draft.name} · {draft.kind}</p><p className="text-sm text-gray-700">{draft.email} · {draft.unionName} · {draft.localName}</p><p className="mt-2 text-sm text-gray-700">{draft.message||"No message provided."}</p></div><span className="text-sm text-gray-600">{new Date(draft.createdAt).toLocaleString()}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Select label="Status" value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</Select><input className="min-h-11 rounded-lg border border-gray-300 px-3" aria-label="Union id" placeholder="Union id" value={draft.unionId||""} onChange={e=>setDraft({...draft,unionId:e.target.value})}/><input className="min-h-11 rounded-lg border border-gray-300 px-3" aria-label="Local id" placeholder="Local id" value={draft.localId||""} onChange={e=>setDraft({...draft,localId:e.target.value})}/></div><Textarea label="Private operator note" rows={3} value={draft.privateNote||""} onChange={e=>setDraft({...draft,privateNote:e.target.value})}/><div className="mt-3 flex flex-wrap items-center gap-3"><Button onClick={()=>void onSave(draft)}>Save review</Button><Link href={`/app/invites?requestId=${draft.id}`} className="text-sm font-semibold text-opseu-blue underline">Open invitations</Link></div></Card>}





