import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import {
  PWA_SERVICE_WORKER_URL,
  PWA_SHELL_CACHE,
  PWA_SHELL_PRECACHE,
  PWA_SW_POLICY,
} from "./shell";

const repoRoot = path.resolve(__dirname, "../../..");
const swPath = path.join(repoRoot, "public", "sw.js");

describe("PWA offline shell constants", () => {
  it("defines a stable cache name and precache list", () => {
    expect(PWA_SHELL_CACHE).toMatch(/^unionops-shell-v\d+$/);
    expect(PWA_SHELL_PRECACHE).toContain("/en/");
    expect(PWA_SHELL_PRECACHE).toContain("/manifest.webmanifest");
    expect(PWA_SHELL_PRECACHE).toContain("/og-image.png");
    expect(PWA_SERVICE_WORKER_URL).toBe("/sw.js");
  });

  it("documents the PC-safe SW policy", () => {
    expect(PWA_SW_POLICY.skipWaiting).toBe(true);
    expect(PWA_SW_POLICY.clientsClaim).toBe(false);
    expect(PWA_SW_POLICY.navigateOnly).toBe(true);
    expect(PWA_SW_POLICY.navigateNetworkFirst).toBe(true);
  });

  it("keeps public/sw.js in sync with shell.ts (installability + offline stub)", () => {
    expect(fs.existsSync(swPath), "public/sw.js must exist").toBe(true);
    const source = fs.readFileSync(swPath, "utf8");

    expect(source).toContain(`const CACHE = "${PWA_SHELL_CACHE}"`);
    for (const entry of PWA_SHELL_PRECACHE) {
      expect(source).toContain(`"${entry}"`);
    }
    expect(source).toMatch(/addEventListener\(\s*["']install["']/);
    expect(source).toMatch(/addEventListener\(\s*["']activate["']/);
    expect(source).toMatch(/addEventListener\(\s*["']fetch["']/);
    expect(source).toContain("skipWaiting");
    // Navigations must stay network-first so Playwright/local never hang on a stale shell.
    expect(source).toContain('request.mode !== "navigate"');
    expect(source).toContain("fetch(request)");
  });

  it("does not claim clients or cache-first non-navigation GETs (PC reload glitch)", () => {
    const raw = fs.readFileSync(swPath, "utf8");
    // Strip comments so policy notes do not false-positive on banned APIs.
    const source = raw
      .replace(/\/\*[\s\S]*?\*\//g, "")
      .replace(/\/\/.*$/gm, "");

    // Mid-load claim + cache-first RSC/assets caused Edge installed PWAs to
    // flash-reload the homescreen. Keep both out of the worker.
    expect(source).not.toMatch(/clients\.claim\s*\(/);
    expect(source).not.toContain("cache.put");
    expect(source).not.toMatch(/caches\.match\(\s*request\s*\)/);

    // Non-navigations must fall through (no respondWith) — early return.
    expect(source).toMatch(
      /if\s*\(\s*request\.mode\s*!==\s*["']navigate["']\s*\)\s*return/,
    );
  });

  it("precaches assets that exist under public/", () => {
    for (const entry of PWA_SHELL_PRECACHE) {
      if (entry === "/en/" || entry === "/manifest.webmanifest") {
        // Generated by Next at runtime / route handlers — not static files.
        continue;
      }
      const absolute = path.join(repoRoot, "public", entry.replace(/^\//, ""));
      expect(fs.existsSync(absolute), `missing precache asset ${absolute}`).toBe(
        true,
      );
    }
  });
});
