"use client";
import { useState } from "react";
import { Input, Textarea } from "@/components/ui/Input";
import { Select } from "@/components/ui/Select";
import { Checkbox } from "@/components/ui/Checkbox";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
type Props = { kind: "local_interest" | "member_access"; locale: string };
const copy = { en:{name:"Your name",email:"Email",union:"Union",local:"Local name or number",role:"Your role",message:"Anything you want us to know?",language:"Preferred language",consent:"I agree that UnionOps may use these details to follow up about beta access.",submit:"Send request",sending:"Sending…",success:"Thanks. Your request was received.",next:"We’ll review the details and follow up. This does not create an account or enroll anyone in a union.",required:"Please complete the required fields.",en:"English",fr:"French",hub:"Officer Hub",portal:"Local Portal",offerings:"What would you like to explore?",localTitle:"Tell us about your local",memberTitle:"Help us find your local",localRole:"President, officer, steward, or organizer"}, fr:{name:"Votre nom",email:"Courriel",union:"Syndicat",local:"Nom ou numéro du local",role:"Votre rôle",message:"Un détail à nous transmettre?",language:"Langue préférée",consent:"J’accepte que UnionOps utilise ces renseignements pour communiquer au sujet de l’accès bêta.",submit:"Envoyer la demande",sending:"Envoi…",success:"Merci. Votre demande a été reçue.",next:"Nous examinerons les renseignements et communiquerons avec vous. Cela ne crée pas de compte et n’inscrit personne à un syndicat.",required:"Veuillez remplir les champs obligatoires.",en:"Anglais",fr:"Français",hub:"Hub des dirigeants",portal:"Portail local",offerings:"Que souhaitez-vous explorer?",localTitle:"Parlez-nous de votre local",memberTitle:"Aidez-nous à trouver votre local",localRole:"Présidence, dirigeance, délégation ou organisation"} };
export function AccessRequestForm({kind,locale}:Props){ const t=copy[locale==="fr"?"fr":"en"]; const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState(""); const [offerings,setOfferings]=useState<string[]>(kind==="member_access"?["local_portal"]:[]); const [language,setLanguage]=useState(locale==="fr"?"fr":"en");
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");const fd=new FormData(e.currentTarget);if(!fd.get("consent")||!offerings.length){setError(t.required);return;}setBusy(true);try{const res=await fetch("/api/access-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({submissionKey:crypto.randomUUID(),kind,name:fd.get("name"),email:fd.get("email"),unionName:fd.get("unionName"),localName:fd.get("localName"),role:fd.get("role"),message:fd.get("message"),offerings,locale:language,consentAccepted:true,website:fd.get("website")})});if(!res.ok){setError((await res.json()).error??t.required);return;}setDone(true);}catch{setError(t.required)}finally{setBusy(false)}}
  if(done)return <Card density="compact"><p className="text-lg font-semibold text-opseu-dark">{t.success}</p><p className="mt-2 text-gray-700">{t.next}</p></Card>;
  return <form onSubmit={submit} className="space-y-4"><h2 className="text-xl font-bold text-opseu-dark">{kind==="local_interest"?t.localTitle:t.memberTitle}</h2><Input name="name" label={t.name} required/><Input name="email" label={t.email} type="email" required/><Input name="unionName" label={t.union} required/><Input name="localName" label={t.local} required/>{kind==="local_interest"?<Input name="role" label={t.role} placeholder={t.localRole}/>:null}{kind==="local_interest"?<fieldset><legend className="text-sm font-medium text-gray-700">{t.offerings}</legend><div className="mt-2 space-y-2"><Checkbox label={t.hub} checked={offerings.includes("officer_hub")} onChange={e=>setOfferings(v=>e.currentTarget.checked?[...new Set([...v,"officer_hub"])]:v.filter(x=>x!=="officer_hub"))}/><Checkbox label={t.portal} checked={offerings.includes("local_portal")} onChange={e=>setOfferings(v=>e.currentTarget.checked?[...new Set([...v,"local_portal"])]:v.filter(x=>x!=="local_portal"))}/></div></fieldset>:null}<Textarea name="message" label={t.message} rows={4}/><Select name="language" label={t.language} value={language} onChange={e=>setLanguage(e.target.value)}><option value="en">{t.en}</option><option value="fr">{t.fr}</option></Select><div className="hidden"><Input name="website" tabIndex={-1} autoComplete="off"/></div><Checkbox name="consent" label={t.consent} required/>{error?<p role="alert" className="text-sm text-red-700">{error}</p>:null}<Button type="submit" disabled={busy} className="min-h-11 w-full">{busy?t.sending:t.submit}</Button></form>;
}
