import type { WebsiteTemplateData } from "@/types/website-template";
import {
  addWebsiteMediaToZip,
  buildWebsiteCss,
  buildWebsiteHtml,
  buildWebsiteJs,
  prepareWebsiteExportData,
  type WebsiteZipHeroImage,
  type WebsiteZipLogo,
} from "@/lib/templates/website/generate-website-zip";

const THEME_URI_PHP =
  "<?php echo esc_url( get_template_directory_uri() ); ?>/assets/";

function sanitizeThemeHeaderField(value: string): string {
  return value
    .replace(/\r?\n/g, " ")
    .replace(/\*\//g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function escapePhpSingleQuoted(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

/** Folder name + text domain: `unionops-local-243`. */
export function wordpressThemeSlug(localNumber: string): string {
  const slug = localNumber
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug ? `unionops-local-${slug}` : "unionops-local";
}

export function wordpressThemeName(
  unionName: string,
  localNumber: string,
): string {
  const cleaned = sanitizeThemeHeaderField(unionName);
  return cleaned || `Local ${localNumber.trim() || "site"}`;
}

function phpFunctionPrefix(slug: string): string {
  return slug.replace(/-/g, "_");
}

export function extractWebsiteBodyMarkup(html: string): string {
  const match = /<body[^>]*>\s*([\s\S]*?)\s*<\/body>/i.exec(html);
  const inner = match?.[1] ?? html;
  return `${inner.replace(/\s*<script[\s\S]*?<\/script>/gi, "").trimEnd()}\n`;
}

export function rewriteWebsiteAssetsForWordpress(html: string): string {
  return html.replaceAll("./assets/", THEME_URI_PHP);
}

export function buildWordpressStyleCss(data: WebsiteTemplateData): string {
  const name = wordpressThemeName(data.unionName, data.localNumber);
  const slug = wordpressThemeSlug(data.localNumber);
  const description = sanitizeThemeHeaderField(
    `One-page local website generated by UnionOps. UnionOps does not host, update, or support WordPress.`,
  );
  const css = buildWebsiteCss(
    data.primaryColor,
    data.secondaryColor,
    data.canvas,
    {
      fontUrlBase: "assets/fonts",
      flatFontFileNames: true,
    },
  );
  return `/*
Theme Name: ${name}
Theme URI: https://unionops.org/tools/website-template
Author: UnionOps
Author URI: https://unionops.org
Description: ${description}
Version: 1.0.0
Requires at least: 6.0
Tested up to: 6.8
Requires PHP: 7.4
Text Domain: ${slug}
License: GNU General Public License v2 or later
License URI: https://www.gnu.org/licenses/gpl-2.0.html
*/

${css}`;
}

export function buildWordpressFunctionsPhp(data: WebsiteTemplateData): string {
  const slug = wordpressThemeSlug(data.localNumber);
  const fn = phpFunctionPrefix(slug);
  const handle = escapePhpSingleQuoted(slug);
  const title = escapePhpSingleQuoted(
    wordpressThemeName(data.unionName, data.localNumber),
  );
  return `<?php
if (!defined('ABSPATH')) {
  exit;
}

function ${fn}_setup() {
  add_theme_support('title-tag');
  add_theme_support('html5', array('search-form', 'gallery', 'caption', 'style', 'script'));
}
add_action('after_setup_theme', '${fn}_setup');

function ${fn}_document_title($title) {
  return '${title}';
}
add_filter('pre_get_document_title', '${fn}_document_title');

function ${fn}_enqueue() {
  $theme = wp_get_theme();
  $ver = $theme->get('Version');
  if (!is_string($ver) || $ver === '') {
    $ver = '1.0.0';
  }
  wp_enqueue_style('${handle}', get_stylesheet_uri(), array(), $ver);
  wp_enqueue_script(
    '${handle}',
    get_template_directory_uri() . '/js/site.js',
    array(),
    $ver,
    true
  );
}
add_action('wp_enqueue_scripts', '${fn}_enqueue');

function ${fn}_dequeue_block_styles() {
  wp_dequeue_style('wp-block-library');
  wp_dequeue_style('wp-block-library-theme');
  wp_dequeue_style('global-styles');
  wp_dequeue_style('classic-theme-styles');
}
add_action('wp_enqueue_scripts', '${fn}_dequeue_block_styles', 100);
`;
}

export function buildWordpressHeaderPhp(): string {
  return `<?php
if (!defined('ABSPATH')) {
  exit;
}
?><!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
  <meta charset="<?php bloginfo('charset'); ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
`;
}

export function buildWordpressFooterPhp(): string {
  return `<?php
if (!defined('ABSPATH')) {
  exit;
}
wp_footer();
?>
</body>
</html>
`;
}

export function buildWordpressIndexPhp(bodyHtml: string): string {
  return `<?php
if (!defined('ABSPATH')) {
  exit;
}
get_header();
?>
${bodyHtml}<?php
get_footer();
`;
}

export function buildWordpressFrontPagePhp(): string {
  return `<?php
if (!defined('ABSPATH')) {
  exit;
}
require get_template_directory() . '/index.php';
`;
}

export function buildWordpressThemeReadme(
  unionName: string,
  localNumber: string,
): string {
  const name = wordpressThemeName(unionName, localNumber);
  return `# ${name} — WordPress theme

Generated by UnionOps Website Template. This is a one-page classic theme that matches the preview.

## UnionOps does not support WordPress

UnionOps does not host WordPress, update WordPress, or help with plugins, permalinks, or security. If you do not already run WordPress, use the GitHub Pages site ZIP instead.

## Install

1. In WordPress: **Appearance → Themes → Add New → Upload Theme**
2. Upload this ZIP and activate the theme
3. Open the site front page — it should match the Website Template preview

Do not submit this theme to wordpress.org. Contact stays a mailto: link; add a form plugin yourself if you need one — we cannot help with that.
`;
}

export async function generateWordpressThemeZip(
  data: WebsiteTemplateData,
  logo?: WebsiteZipLogo | null,
  heroImage?: WebsiteZipHeroImage | null,
): Promise<Blob> {
  const JSZip = (await import("jszip")).default;
  const zip = new JSZip();
  const exportData = prepareWebsiteExportData(data, logo, heroImage);
  const slug = wordpressThemeSlug(data.localNumber);
  const root = zip.folder(slug);
  if (!root) {
    throw new Error("Could not create the WordPress theme folder.");
  }

  const bodyHtml = rewriteWebsiteAssetsForWordpress(
    extractWebsiteBodyMarkup(buildWebsiteHtml(exportData)),
  );

  root.file("style.css", buildWordpressStyleCss(exportData));
  root.file("functions.php", buildWordpressFunctionsPhp(exportData));
  root.file("header.php", buildWordpressHeaderPhp());
  root.file("footer.php", buildWordpressFooterPhp());
  root.file("index.php", buildWordpressIndexPhp(bodyHtml));
  root.file("front-page.php", buildWordpressFrontPagePhp());
  root.file("js/site.js", buildWebsiteJs());
  root.file(
    "README.md",
    buildWordpressThemeReadme(data.unionName, data.localNumber),
  );
  await addWebsiteMediaToZip(root, exportData, logo, heroImage);

  return zip.generateAsync({ type: "blob" });
}
